# █▀█ ▀█▀ ▀
# ▀▀█ ░█░ ▄
# -- -- --
# Configures Qt framework settings to match the GTK theme.

{ ... }:
{
  qt = {
    enable = true;
    platformTheme.name = "gtk3";
  };

  home.sessionVariables = {
    # Ensure Qt5 and Qt6 applications use the GTK3 platform theme
    # so they inherit the colors generated by DMS (matugen).
    QT_QPA_PLATFORMTHEME = "gtk3";
    QT_QPA_PLATFORMTHEME_QT6 = "gtk3";
  };
}
