[book]
authors = ["Stepan Zhukovsky"]
language = "en"
src = "src"
title = "NixOS configurations Documentation"

[output.html]
git-repository-url = "https://github.com/MOIS3Y/nixos-configurations"
edit-url-template = "https://github.com/MOIS3Y/nixos-configurations/edit/main/docs/{path}"
preferred-dark-theme = "mocha"
additional-css = ["theme/catppuccin.css"]
theme = "theme"
